---
title: "ELA vs Normal -- c-fos vs MEMRI Comparison"
subtitle: "v2-No Whole-head Rigid Body, Warped Images"
author: "Taylor W. Uselman"
date: "Original Date: 04/10/2024, Last Modified Date: `r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document: 
    toc: true
    number_sections: true
    toc_depth: 5
    code_folding: show
    theme: cerulean
    highlight: tango
  pdf_document:
    df_print: kable
fontsize: 12pt
geometry: margin=0.25in
always_allow_html: yes
---

```{R setup, include=FALSE}
#### Format RMarkdown Parameters
knitr::opts_chunk$set(comment = NA, message = FALSE, warning = FALSE, width = 100)
knitr::opts_chunk$set(fig.align = "center", fig.height = 5, fig.width = 12) #### 4" x 8" unless otherwise specific
knitr::opts_chunk$set(cache = TRUE) #### cache = FALSE may be needed, but be aware... this document will take a very long time to knit.
knitr::opts_chunk$set(echo = TRUE) #### Code output is echoed/output immediately after the code in the .html file.


wdir <- "Local Directory" # USER INPUT for directory where files are located
setwd(wdir)

#### ROI Input Data Directory
dat_dir = paste0(wdir,"/OutputData")

#### Processed Data Directory
res_dir = paste0(wdir,"/R_Analysis/Results")

#### Graphs/Figures Directory
img_dir = paste0(wdir,"/R_Analysis/Images")
if (!dir.exists(img_dir)) {dir.create(img_dir)}
if (!dir.exists(paste0(img_dir,"/Boxplots"))) {dir.create(paste0(img_dir,"/Boxplots"))}

version = 1
output_prefix = paste0(format(Sys.time(), '%y%m%d'),"-v",version)
anyfiles = list.files(path = paste0(img_dir,"/Boxplots"), pattern = "output_prefix")
while ((length(anyfiles)>0) == T){
  version = version + 1
  output_prefix = paste0(format(Sys.time(), '%y%m%d'),"-v",version)
  anyfiles = list.files(path = paste0(img_dir,"/Boxplots"), pattern = "output_prefix")
}

#### Libraries needed
#### citation() --> use this to determine citations for each package

#### Data Processing
library(openxlsx)
library(tidyverse)
library(reshape2)

#### Data Graphics
library(ggplot2)
library(ggnewscale)
library(gridExtra)
library(corrplot)
library(RColorBrewer)
library(gridGraphics)
library(ggpubr)

#### Data Analysis
library(nlme) #### Non-linear Mixed Effects Models
library(car) #### Diagnostics
library(emmeans) #### Post-hoc pair-wise t-tests from NLME output, with multiple comparisons correction

source(paste0(wdir,"/R_Analysis/","ada_functions.R"))

#### Set Color Scheme
col_norm = "cyan4"
col_ela =  "goldenrod3"
col_d9 = "limegreen"
```

# Summary {.tabset .tabset-fade .tabset-pills}

Below are sections for loading and analyzing c-fos IHC count data (Section 1: '## c-fos Counts'), MEMRI ROI signal intensity data (Section 2: '## MEMRI SI'), and then performing correlations between the two (Section 3: '## Correlations between c-fos and MEMRI').

## c-fos Counts  {.tabset .tabset-fade .tabset-pills}

### Load and Process Data {.tabset .tabset-fade .tabset-pills}

#### Load Data
```{R}
filename <- "240411_c-fos_GridCounts-TWU.xlsx"

dat_cfos_count = read.xlsx(
    xlsxFile = paste0(wdir,"/R_Analysis/",filename)
  , sheet = "long.df.voxels"
  , colNames = T
  , na.strings = NA)
```

#### Process Data

```{R}
  #### FORMAT DATA FRAME
  dat_cfos_count <- dat_cfos_count %>%
    mutate(
      ELA = factor(
        Group,
        levels = c("ELA","Normal"),
        labels = c("ELA","Normal")),
      ROI = factor(ROI,
                   levels = c("CS","MB","HYP","THA"),
                   labels = c("CS","MB","HYP","THA")
                   ),
      AnimNum = factor(ID,
                       levels = c("03","04","05","06","07","08","A","D","F","I","K"),
                       labels = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11)),
      VoxelNum = factor(VoxelNum),
      Count = as.numeric(cfos_count)
    ) %>% 
    arrange(ROI,ELA,VoxelNum) %>%
    select(AnimNum,VoxelNum,ELA,ROI,Count)

knitr::kable(summary(dat_cfos_count))
str(dat_cfos_count)
```  

#### Summarize Data

```{R}
dat_cfos_count_sum <- dat_cfos_count %>%
  group_by(
    ROI, ELA
  ) %>%
  summarise(
    M = mean(Count) %>% round(.,2),
    SD = sd(Count) %>% round(.,2),
    SEM = (SD / sqrt(n())) %>% round(.,2)
  ) %>% data.frame()
knitr::kable(summary(dat_cfos_count_sum), caption = "Summary of Data by Individual")


dat_cfos_count_sum2 <- dat_cfos_count %>%
  group_by(
    ROI, VoxelNum
  ) %>%
  summarise(
    M = mean(Count) %>% round(.,2),
    SD = sd(Count) %>% round(.,2),
    SEM = (SD / sqrt(n())) %>% round(.,2)
  ) %>% data.frame()
knitr::kable(summary(dat_cfos_count_sum2), caption = "Summary of Data by Voxel Location")


dat_cfos_count_sum3 <- dat_cfos_count %>%
  group_by(
    ROI, ELA, VoxelNum
  ) %>%
  summarise(
    M = mean(Count) %>% round(.,2),
    SD = sd(Count) %>% round(.,2),
    SEM = (SD / sqrt(n())) %>% round(.,2)
  ) %>% data.frame()
knitr::kable(summary(dat_cfos_count_sum3), caption = "Summary of Data by Individual and Voxel Location")


cfos_count_sum_total <- dat_cfos_count %>%
  group_by(ELA) %>%
  summarise(
    M = mean(Count) %>% round(.,2),
    SD = sd(Count) %>% round(.,2),
    COV = (SD/M) %>% round(.,3)
  ) %>% data.frame()
knitr::kable((cfos_count_sum_total), caption = "Summary of all measured c-fos count data")
```


### Analysis {.tabset .tabset-fade .tabset-pills}

#### Graph Pairwise Comparisons Plots

```{R,fig.height = 5, fig.width = 6}
#### Box Plot
######## Count
p1 = ggplot(data = dat_cfos_count %>% filter(ROI %in% c("CS","MB"), ELA == "ELA"),
            aes(x=factor(ROI), y=Count, color=factor(ELA), fill=factor(ELA)))
p1 = p1 + geom_hline(yintercept=0, linetype="dashed", color="black", alpha =0.25, linewidth=0.5)
p1 = p1 + geom_point(size=0.35, alpha=0.75)#### position=position_dodge(0.75)
# p = p + stat_summary(fun.data = mean_cl_boot, fun.args=list(conf.int=(1-(0.05))),
                     # geom="errorbar", width = 0.375, linewidth=0.25, color="red3", alpha=0.75) ####position = position_dodge(0.75)
# p = p + stat_summary(fun=mean, geom="point", shape=18, size=1, color="red3", alpha=0.75) ####position=position_dodge(0.75)
p1 = p1 + geom_boxplot(width=0.65, outlier.shape=NA, alpha=0.25, size=0.25) ####position=position_dodge(0.75)
p1 = p1 + scale_fill_manual(values = c("darkviolet"))#col_ela))#, col_norm))
p1 = p1 + scale_color_manual(values = c("darkviolet"))#col_ela))#, col_norm))
p1 = p1 + scale_y_continuous(limits=c(0,30), breaks=seq(0,30,10), expand=c(0,0,0,0))
# p = p + facet_grid(. ~ ELA)
p1 = p1 + labs(title = "", x = "", y = "")
p1 = p1 + theme_classic()
p1 = p1 + theme(plot.title = element_blank()
              , axis.title.x = element_blank()
              , axis.text.x = element_text(angle=45,size=8,family="sans",face="bold",vjust=0.9,hjust=0.75)
              , axis.title.y = element_blank()#text(hjust=1,size=9,family="sans")
              , axis.text.y = element_text(size=8,family="sans",face="bold")
              , strip.background = element_rect(fill="grey90")
              , strip.text = element_text(size=8,family="sans",face="bold")
              , panel.grid.major.x = element_blank()
              , panel.grid.major.y = element_blank()#element_line(color="grey75", linewidth = 0.25, linetype=2)
              ##, panel.grid.minor.y = element_blank()
              # , panel.border = element_rect(colour = "black", fill=NA, linewidth=0.5)
              , legend.position = "none")
ggsave(filename=paste0(output_prefix,"_ELA_cfos_CS-MB_Counts_box_n6.png")
       ,plot=p1
       ,device="png"
       ,path=paste0(img_dir,"/BoxPlots")
       ,units="in", width=0.75, height=1.45, dpi=320)

p2 = ggplot(data = dat_cfos_count %>% filter(ROI %in% c("CS","MB"), ELA == "Normal"),
            aes(x=factor(ROI), y=Count, color=factor(ELA), fill=factor(ELA)))
p2 = p2 + geom_hline(yintercept=0, linetype="dashed", color="black", alpha =0.25, linewidth=0.5)
p2 = p2 + geom_point(size=0.35, alpha=0.75)

p2 = p2 + geom_boxplot(width=0.65, outlier.shape=NA, alpha=0.25, size=0.25) 
p2 = p2 + scale_fill_manual(values = c("violet"))
p2 = p2 + scale_color_manual(values = c("violet"))
p2 = p2 + scale_y_continuous(limits=c(0,30), breaks=seq(0,30,10), expand=c(0,0,0,0))

p2 = p2 + labs(title = "", x = "", y = "")
p2 = p2 + theme_classic()
p2 = p2 + theme(plot.title = element_blank()
              , axis.title.x = element_blank()
              , axis.text.x = element_text(angle=45,size=8,family="sans",face="bold",vjust=0.9,hjust=0.75)
              , axis.title.y = element_blank()
              , axis.text.y = element_text(size=8,family="sans",face="bold")
              , strip.background = element_rect(fill="grey90")
              , strip.text = element_text(size=8,family="sans",face="bold")
              , panel.grid.major.x = element_blank()
              , panel.grid.major.y = element_blank()
              , legend.position = "none")
ggsave(filename=paste0(output_prefix,"_Normal_cfos_CS-MB_Counts_box_n6.png")
       ,plot=p2
       ,device="png"
       ,path=paste0(img_dir,"/BoxPlots")
       ,units="in", width=0.75, height=1.45, dpi=320)




p3 = ggplot(data = dat_cfos_count %>% filter(ROI %in% c("HYP","THA"), ELA == "ELA"),
            aes(x=factor(ROI), y=(Count), color=factor(ELA), fill=factor(ELA)))
p3 = p3 + geom_hline(yintercept=0, linetype="dashed", color="black", alpha =0.25, linewidth=0.5)
p3 = p3 + geom_point(size=0.35, alpha=0.75)
p3 = p3 + geom_boxplot(width=0.65, outlier.shape=NA, alpha=0.25, size=0.25) 
p3 = p3 + scale_fill_manual(values = c("darkviolet"))
p3 = p3 + scale_color_manual(values = c("darkviolet"))
p3 = p3 + scale_y_continuous(limits=c(0,30), breaks=seq(0,30,10), expand=c(0,0,0,0))
p3 = p3 + labs(title = "", x = "", y = "")
p3 = p3 + theme_classic()
p3 = p3 + theme(plot.title = element_blank()
              , axis.title.x = element_blank()
              , axis.text.x = element_text(angle=45,size=8,family="sans",face="bold",vjust=0.9,hjust=0.75)
              , axis.title.y = element_blank()
              , axis.text.y = element_text(size=8,family="sans",face="bold")
              , strip.background = element_rect(fill="grey90")
              , strip.text = element_text(size=8,family="sans",face="bold")
              , panel.grid.major.x = element_blank()
              , panel.grid.major.y = element_blank()
              , legend.position = "none")
ggsave(filename=paste0(output_prefix,"_ELA_cfos_HYP-THA_Counts_box_n6.png")
       ,plot=p3
       ,device="png"
       ,path=paste0(img_dir,"/BoxPlots")
       ,units="in", width=0.75, height=1.45, dpi=320)


p4 = ggplot(data = dat_cfos_count %>% filter(ROI %in% c("HYP","THA"), ELA == "Normal"),
            aes(x=factor(ROI), y=(Count), color=factor(ELA), fill=factor(ELA)))
p4 = p4 + geom_hline(yintercept=0, linetype="dashed", color="black", alpha =0.25, linewidth=0.5)
p4 = p4 + geom_point(size=0.35, alpha=0.75)
p4 = p4 + geom_boxplot(width=0.65, outlier.shape=NA, alpha=0.25, size=0.25)
p4 = p4 + scale_fill_manual(values = c("violet"))
p4 = p4 + scale_color_manual(values = c("violet"))
p4 = p4 + scale_y_continuous(limits=c(0,30), breaks=seq(0,30,10), expand=c(0,0,0,0))

p4 = p4 + labs(title = "", x = "", y = "")
p4 = p4 + theme_classic()
p4 = p4 + theme(plot.title = element_blank()
              , axis.title.x = element_blank()
              , axis.text.x = element_text(angle=45,size=8,family="sans",face="bold",vjust=0.9,hjust=0.75)
              , axis.title.y = element_blank()
              , axis.text.y = element_text(size=8,family="sans",face="bold")
              , strip.background = element_rect(fill="grey90")
              , strip.text = element_text(size=8,family="sans",face="bold")
              , panel.grid.major.x = element_blank()
              , panel.grid.major.y = element_blank()
              , legend.position = "none")
ggsave(filename=paste0(output_prefix,"_Normal_cfos_HYP-THA_Counts_box_n6.png")
       ,plot=p4
       ,device="png"
       ,path=paste0(img_dir,"/BoxPlots")
       ,units="in", width=0.75, height=1.45, dpi=320)

grid.arrange(grobs = list(p1, p2, p3, p4), nrow=2, ncol=2)
```

#### Mixed Effect Models {.tabset .tabset-fade .tabset-pills}

__Model Setup:__ A repeated measures ANOVA (mixed effects model) will be used for all analyses.

Mixed Effect Model with Compound Symmetry in covariance matrix assumed. (Random intercept/Repeated Measure ANOVA).

__Model:__

$$
  Y_{ij} = (\mu_0 + \alpha_j) + (S_i + e_{ij})
$$

Where fixed effects are `ROI` and `ELA`, and random effects are `Animal` and `Voxel Number`.

Random effects here are used to control for Animal-to-Animal and Voxel-to-Voxel variance separately. 

##### Assessing Residuals 

```{R, fig.height = 4, fig.width = 6}
dir_tmp = paste0(output_prefix,"_cfos_ROI_analysis_counts")

if (!dir.exists(paste0(img_dir,"/Residuals/"))) {dir.create(paste0(img_dir,"/Residuals"))}
if (!dir.exists(paste0(img_dir,"/Residuals/",dir_tmp))) {dir.create(paste0(img_dir,"/Residuals/",dir_tmp))}

  lme.e.mte.rma <- lme(sqrt(Count) ~ ROI
                     , random = list((~1|AnimNum),(~1|VoxelNum))
                     , method = "REML"
                     , control = lmeControl(opt = 'optim')
                     , data = dat_cfos_count %>% filter(ELA == "ELA")
                     )
  lme.n.mte.rma <- lme(sqrt(Count) ~ ROI
                     , random = list((~1|AnimNum),(~1|VoxelNum))
                     , method = "REML"
                     , control = lmeControl(opt = 'optim')
                     , data = dat_cfos_count %>% filter(ELA == "Normal")
                     )
  for (group in c("ELA","Normal")) {
    if (group == "ELA"){
      lm.tmp = lme.e.mte.rma
    } else {
      lm.tmp = lme.n.mte.rma
    }
    cnt=1
    for (res in 1:dim(lm.tmp$residuals)[2]) {
      #### Residual Effect Type
      print(restype <- colnames(lm.tmp$residuals)[res])
      #### QQ Plot
      qqPlot(lm.tmp$residuals[,res], main=paste0("QQPlot for ",restype," in", group))
      jpeg(file=paste0(paste0(img_dir,"/Residuals/"),dir_tmp,"/",output_prefix,"QQnorm_",restype,"-",group,".jpeg"),
         width = 4, height = 4, units = "in", res = 300)
      qqPlot(lm.tmp$residuals[,res], main=paste0("QQPlot for ",restype," in", group))
      dev.off()
      ######## Bootstrapped Sampling Distribution of Residuals
      jpeg(file=paste0(paste0(img_dir,"/Residuals/"),dir_tmp,"/",output_prefix,"BootStrappedSampDist_",restype,"-",group,".jpeg"),
         width = 4, height = 4, units = "in", res = 300)
      bs_one_samp_dist(lm.tmp$residuals[,res])
      dev.off()
      #### Variance of Residuals by Fitted
      plot(lm.tmp$fitted[(1:dim(lm.tmp$residuals)[1])*cnt], lm.tmp$residuals[,res],
              main=paste0(restype," in", group, " Residuals by Fitted"))
      jpeg(file=paste0(paste0(img_dir,"/Residuals/"),dir_tmp,"/",output_prefix,"InHVar_Fitted",restype,"-",group,".jpeg"),
           width = 4, height = 4, units = "in", res = 300)
      plot(lm.tmp$fitted[(1:dim(lm.tmp$residuals)[1])*cnt], lm.tmp$residuals[,res],
              main=paste0(restype," in", group, " Residuals by Fitted"))
      dev.off()
      #### Variance Plot by ROI
      plot(lm.tmp$data$ROI, lm.tmp$residuals[,res],
           main=paste0(restype," in", group," Residuals by ROI"))
      jpeg(file=paste0(paste0(img_dir,"/Residuals/"),dir_tmp,"/",output_prefix,"InHVar_ROI",restype,"-",group,".jpeg"),
           width = 4, height = 4, units = "in", res = 300)
      plot(lm.tmp$data$ROI, lm.tmp$residuals[,res],
           main=paste0(restype," in", group," Residuals by ROI"))
      dev.off()
      cnt=cnt+1
    }
  }
```

##### Results of Linear Model and Post-Comparisons

```{R}
# ANOVA Results
  print("ELA")
  print(a.e.res <- Anova(lme.e.mte.rma, type="III"))
  print("Normal")
  print(a.n.res <- Anova(lme.n.mte.rma, type="III"))  

# Post-hoc Tests
## ELA
  #### Contrast Family ####1: Withing Group Differences between ROIs
  cont.cfos.e <- emmeans(lme.e.mte.rma, specs = "ROI")#, by = c("ELA"))
  ######## Calculate T/P-values
  results_cfos1 = cont.cfos.e %>% pairs(adjust = "none") %>% data.frame()
  ######## FDR Adjustment of P-values for Family of Pairwise Comparisons
  results_cfos1$p.value.fdr = ((cont.cfos.e %>% pairs(adjust = "fdr")) %>% as.data.frame())$p.value
  ######## Calculcate Cohen's D
  results_cfos1$CohD = abs(effectsize::t_to_d(as.data.frame(pairs(cont.cfos.e))$t.ratio,  
                                    rep(6,6),
                                    paired = T)$d
                 )
  ######## Update Data frame Results Output  
  results_cfos1 <- results_cfos1 %>%
    mutate(
      MeanDiff = (estimate) %>% round(.,2),
      SE = (SE) %>% round(.,2),
      T.value = round(t.ratio,2),
      CohD = round(CohD,2),
      P.value = round(p.value,5),
      P.value.fdr = round(p.value.fdr,5),
      SigLevel = ifelse(P.value.fdr > 0.1, "n.s.",
                        ifelse(P.value.fdr > 0.05, "~",
                               ifelse(P.value.fdr > 0.01, "*",
                                      ifelse(P.value.fdr > 0.001, "**", "***"))))
    ) %>%
    select(contrast,MeanDiff,SE,df,T.value,CohD,P.value,P.value.fdr,SigLevel)
  knitr::kable(results_cfos1, caption = "c-fos Count Differences between ROIs within ELA")  
  
  
## Normal
  #### Contrast Family ####1: Withing Group Differences between ROIs
  cont.cfos.n <- emmeans(lme.n.mte.rma, specs = "ROI")#, by = c("ELA"))
  ######## Calculate T/P-values
  results_cfos2 = cont.cfos.n %>% pairs(adjust = "none") %>% data.frame()
  ######## FDR Adjustment of P-values for Family of Pairwise Comparisons
  results_cfos2$p.value.fdr = ((cont.cfos.n %>% pairs(adjust = "fdr")) %>% as.data.frame())$p.value
  ######## Calculcate Cohen's D
  results_cfos2$CohD = abs(effectsize::t_to_d(as.data.frame(pairs(cont.cfos.n))$t.ratio,  
                                    rep(6,6),
                                    paired = T)$d
                 )
  ######## Update Data frame Results Output  
  results_cfos2 <- results_cfos2 %>%
    mutate(
      MeanDiff = (estimate) %>% round(.,2),
      SE = (SE) %>% round(.,2),
      T.value = round(t.ratio,2),
      CohD = round(CohD,2),
      P.value = round(p.value,5),
      P.value.fdr = round(p.value.fdr,5),
      SigLevel = ifelse(P.value.fdr > 0.1, "n.s.",
                        ifelse(P.value.fdr > 0.05, "~",
                               ifelse(P.value.fdr > 0.01, "*",
                                      ifelse(P.value.fdr > 0.001, "**", "***"))))
    ) %>%
    select(contrast,MeanDiff,SE,df,T.value,CohD,P.value,P.value.fdr,SigLevel)
  knitr::kable(results_cfos2, caption = "c-fos Count Differences between ROIs within Normal")  
```



#### T-tests

```{R}
df_test <- dat_cfos_count %>% 
  mutate(sqrCount = sqrt(Count)) 
  

g1.r1.dat = df_test %>% filter(ELA == "ELA", ROI == "CS") %>% select(AnimNum,sqrCount)
g1.r2.dat = df_test %>% filter(ELA == "ELA", ROI == "MB") %>% select(AnimNum,sqrCount)
g1.r2_r1.dat = data.frame(
  AnimNum = g1.r1.dat$AnimNum,
  Diff = g1.r2.dat$sqrCount - g1.r1.dat$sqrCount 
)

tout = t.test(g1.r2_r1.dat$Diff, paired = F, var.equal = F)
print(tout)
effectsize::t_to_d(tout$statistic,6,paired=T) %>% abs() %>% pull(d) %>% round(.,2)

g1.r3.dat = df_test %>% filter(ELA == "ELA", ROI == "HYP") %>% pull(sqrCount)
g1.r4.dat = df_test %>% filter(ELA == "ELA", ROI == "THA") %>% pull(sqrCount)
bs_two_samp_diff_dist(g1.r3.dat,g1.r4.dat)
qqPlot(g1.r3.dat)
qqPlot(g1.r4.dat)
leveneTest(sqrCount ~ ROI, data = df_test %>% filter(ELA == "ELA", ROI %in% c("HYP","THA")))
tout = t.test(g1.r3.dat,g1.r4.dat, paired = T, var.equal = T)
print(tout)
effectsize::t_to_d(tout$statistic,6,paired=T) %>% abs() %>% pull(d) %>% round(.,2)

g2.r1.dat = df_test %>% filter(ELA == "Normal", ROI == "CS") %>% pull(sqrCount)
g2.r2.dat = df_test %>% filter(ELA == "Normal", ROI == "MB") %>% pull(sqrCount)
bs_two_samp_diff_dist(g2.r1.dat,g2.r2.dat)
qqPlot(g2.r1.dat)
qqPlot(g2.r2.dat)
bartlett.test(sqrCount ~ ROI, data = df_test %>% filter(ELA == "Normal", ROI %in% c("CS","MB")))
t.test(g2.r1.dat,g2.r2.dat, paired = F, var.equal = F)

g2.r3.dat = df_test %>% filter(ELA == "Normal", ROI == "HYP") %>% pull(sqrCount)
g2.r4.dat = df_test %>% filter(ELA == "Normal", ROI == "THA") %>% pull(sqrCount)
bs_two_samp_diff_dist(g2.r3.dat,g2.r4.dat)
qqPlot(g2.r3.dat)
qqPlot(g2.r4.dat)
bartlett.test(sqrCount ~ ROI, data = df_test %>% filter(ELA == "Normal", ROI %in% c("HYP","THA")))
t.test(g2.r3.dat,g2.r4.dat, paired = F, var.equal = T)
```



## MEMRI SI {.tabset .tabset-fade .tabset-pills}

### Load and Process Data {.tabset .tabset-fade .tabset-pills}

#### Load Data
```{R}
filename <- "ELA_Normal_cfos_ROI.csv"
header <- c("IMAGE","ROI"
           ,c("ELA","Condition","VoxelNum") 
           ,"MEAN","BLANK") 

dat_cfos_roi = read.csv2(paste0(dat_dir,"/",filename)
                      ,header = F
                      ,na.strings = NA
                      ,sep = ","
                      ,col.names = header)


```

#### Process Data

```{R}
dat_cfos_roi = dat_cfos_roi[,-which(colnames(dat_cfos_roi) == "BLANK")] 

  #### FORMAT DATA FRAME
  dat_cfos_roi <- dat_cfos_roi %>%
    mutate(
      Condition = factor(
        Condition,
        levels = c("D9")),
      ELA = factor(
        ELA,
        levels = c("ELA","Normal"),
        labels = c("ELA","Normal")),
      ROI = factor(ROI,
                   levels = c("CS","MB","HYP","THA"),
                   labels = c("CS","MB","HYP","THA")
                   ),
      ID = factor(parse_number(IMAGE)),
      VoxelNum = factor(VoxelNum),
      MEAN = as.numeric(MEAN)
    ) %>%
    arrange(ROI,ELA,Condition,VoxelNum) %>%
    group_by(
      Condition,
      ROI,
      VoxelNum
    ) %>%
    mutate(
      AnimNum = factor(1:n())
    ) %>%
    ungroup() %>%
    select(AnimNum,VoxelNum,ELA,Condition,ROI,MEAN) %>%
    filter(
      AnimNum %in% c(1:6,13,14,15,17,18)
    )
  
Group_Intensity_Summary <- dat_cfos_roi %>% 
  filter(ROI %in% c("CS","MB","HYP","THA"),
         Condition == "D9") %>% 
  group_by(ELA) %>%
  summarize(
    m = mean(MEAN) %>% round(.,2),
    s = sd(MEAN) %>% round(.,2),
    cov = (s/m) %>% round(.,3)
    )
knitr::kable((Group_Intensity_Summary), caption = "Summary of all measured MEMRI SI data from c-fos stained brains")  

COV_comparison = data.frame(
  "ELA" = Group_Intensity_Summary$ELA,
  "COVdiff" = (Group_Intensity_Summary$cov - cfos_count_sum_total$COV),
  "COVperc" = (Group_Intensity_Summary$cov - cfos_count_sum_total$COV)/(cfos_count_sum_total$COV),
  "COVfrac" = Group_Intensity_Summary$cov / cfos_count_sum_total$COV)
knitr::kable((COV_comparison[,2:4] %>% colMeans()), caption = "Comparison of the Coefficient of Variation between MEMRI SI and c-fos counts for each group")  
  

dat_cfos_roi_sub <- dat_cfos_roi %>%
  filter(Condition == "D9",
         ROI %in% c("CS","MB","HYP","THA")) %>%
  mutate(
    M_S = MEAN / ifelse(ELA == "ELA", Group_Intensity_Summary$s[1], Group_Intensity_Summary$s[2])
  )

knitr::kable(summary(dat_cfos_roi_sub))



df_test <- dat_cfos_roi_sub

```  

#### Subset Data

```{R}
dat_cfos_roi_sub <- df_test %>% 
  filter(
    (Condition == "D9"),
    ROI %in% c("CS","MB","HYP","THA")
    ) %>%
  mutate(
    Condition = droplevels.factor(Condition),
    ROI = droplevels.factor(ROI)
    )
knitr::kable(summary(dat_cfos_roi_sub))
```



### Analysis {.tabset .tabset-fade .tabset-pills}

#### Graph Pairwise Comparisons Plots

```{R, fig.height = 5, fig.width = 6}
#### Box Plot
######## MEAN_BL
p1 = ggplot(data = dat_cfos_roi_sub %>% filter(ROI %in% c("CS","MB"), ELA == "ELA"),
            aes(x=factor(ROI), y=M_S, color=factor(ELA), fill=factor(ELA)))
p1 = p1 + geom_hline(yintercept=0, linetype="dashed", color="black", alpha =0.25, linewidth=0.5)
p1 = p1 + geom_point(size=0.35, alpha=0.75)
p1 = p1 + geom_boxplot(width=0.65, outlier.shape=NA, alpha=0.25, size=0.25)
p1 = p1 + scale_fill_manual(values = c(col_ela))
p1 = p1 + scale_color_manual(values = c(col_ela))
p1 = p1 + scale_y_continuous(limits=c(0,12), breaks=seq(0,12,3), expand=c(0,0,0,0))
p1 = p1 + labs(title = "", x = "", y = "")
p1 = p1 + theme_classic()
p1 = p1 + theme(plot.title = element_blank()
              , axis.title.x = element_blank()
              , axis.text.x = element_text(angle=45,size=8,family="sans",face="bold",vjust=0.9,hjust=0.75)
              , axis.title.y = element_blank()
              , axis.text.y = element_text(size=8,family="sans",face="bold")
              , strip.background = element_rect(fill="grey90")
              , strip.text = element_text(size=8,family="sans",face="bold")
              , panel.grid.major.x = element_blank()
              , panel.grid.major.y = element_blank()
              , legend.position = "none")
p1
# ggsave(filename=paste0(output_prefix,"_ELA_cfos_CS-MB_M_S_box_n6.png")
#        ,plot=p1
#        ,device="png"
#        ,path=paste0(img_dir,"/BoxPlots")
#        ,units="in", width=0.75, height=1.45, dpi=320)

p2 = ggplot(data = dat_cfos_roi_sub %>% filter(ROI %in% c("CS","MB"), ELA == "Normal"),
            aes(x=factor(ROI), y=M_S, color=factor(ELA), fill=factor(ELA)))
p2 = p2 + geom_hline(yintercept=0, linetype="dashed", color="black", alpha =0.25, linewidth=0.5)
p2 = p2 + geom_point(size=0.35, alpha=0.75)
p2 = p2 + geom_boxplot(width=0.65, outlier.shape=NA, alpha=0.25, size=0.25)
p2 = p2 + scale_fill_manual(values = c(col_norm))
p2 = p2 + scale_color_manual(values = c(col_norm))
p2 = p2 + scale_y_continuous(limits=c(0,12), breaks=seq(0,12,3), expand=c(0,0,0,0))
p2 = p2 + labs(title = "", x = "", y = "")
p2 = p2 + theme_classic()
p2 = p2 + theme(plot.title = element_blank()
              , axis.title.x = element_blank()
              , axis.text.x = element_text(angle=45,size=8,family="sans",face="bold",vjust=0.9,hjust=0.75)
              , axis.title.y = element_blank()
              , axis.text.y = element_text(size=8,family="sans",face="bold")
              , strip.background = element_rect(fill="grey90")
              , strip.text = element_text(size=8,family="sans",face="bold")
              , panel.grid.major.x = element_blank()
              , panel.grid.major.y = element_blank()
              , legend.position = "none")
p2
# ggsave(filename=paste0(output_prefix,"_Normal_cfos_CS-MB_M_S_box_n6.png")
#        ,plot=p2
#        ,device="png"
#        ,path=paste0(img_dir,"/BoxPlots")
#        ,units="in", width=0.75, height=1.45, dpi=320)




p3 = ggplot(data = dat_cfos_roi_sub %>% filter(ROI %in% c("HYP","THA"), ELA == "ELA"),
            aes(x=factor(ROI), y=M_S, color=factor(ELA), fill=factor(ELA)))
p3 = p3 + geom_hline(yintercept=0, linetype="dashed", color="black", alpha =0.25, linewidth=0.5)
p3 = p3 + geom_point(size=0.35, alpha=0.75)
p3 = p3 + geom_boxplot(width=0.65, outlier.shape=NA, alpha=0.25, size=0.25) 
p3 = p3 + scale_fill_manual(values = c(col_ela))
p3 = p3 + scale_color_manual(values = c(col_ela))
p3 = p3 + scale_y_continuous(limits=c(0,12), breaks=seq(0,12,3), expand=c(0,0,0,0))
p3 = p3 + labs(title = "", x = "", y = "")
p3 = p3 + theme_classic()
p3 = p3 + theme(plot.title = element_blank()
              , axis.title.x = element_blank()
              , axis.text.x = element_text(angle=45,size=8,family="sans",face="bold",vjust=0.9,hjust=0.75)
              , axis.title.y = element_blank()
              , axis.text.y = element_text(size=8,family="sans",face="bold")
              , strip.background = element_rect(fill="grey90")
              , strip.text = element_text(size=8,family="sans",face="bold")
              , panel.grid.major.x = element_blank()
              , panel.grid.major.y = element_blank()
              , legend.position = "none")
p3
# ggsave(filename=paste0(output_prefix,"_ELA_cfos_HYP-THA_M_S_box_n6.png")
#        ,plot=p3
#        ,device="png"
#        ,path=paste0(img_dir,"/BoxPlots")
#        ,units="in", width=0.75, height=1.45, dpi=320)


p4 = ggplot(data = dat_cfos_roi_sub %>% filter(ROI %in% c("HYP","THA"), ELA == "Normal"),
            aes(x=factor(ROI), y=M_S, color=factor(ELA), fill=factor(ELA)))
p4 = p4 + geom_hline(yintercept=0, linetype="dashed", color="black", alpha =0.25, linewidth=0.5)
p4 = p4 + geom_point(size=0.35, alpha=0.75)
p4 = p4 + geom_boxplot(width=0.65, outlier.shape=NA, alpha=0.25, size=0.25) 
p4 = p4 + scale_fill_manual(values = c(col_norm))
p4 = p4 + scale_color_manual(values = c(col_norm))
p4 = p4 + scale_y_continuous(limits=c(0,12), breaks=seq(0,12,3), expand=c(0,0,0,0))
p4 = p4 + labs(title = "", x = "", y = "")
p4 = p4 + theme_classic()
p4 = p4 + theme(plot.title = element_blank()
              , axis.title.x = element_blank()
              , axis.text.x = element_text(angle=45,size=8,family="sans",face="bold",vjust=0.9,hjust=0.75)
              , axis.title.y = element_blank()
              , axis.text.y = element_text(size=8,family="sans",face="bold")
              , strip.background = element_rect(fill="grey90")
              , strip.text = element_text(size=8,family="sans",face="bold")
              , panel.grid.major.x = element_blank()
              , panel.grid.major.y = element_blank()
              , legend.position = "none")
p4
# ggsave(filename=paste0(output_prefix,"_Normal_cfos_HYP-THA_M_S_box_n6.png")
#        ,plot=p4
#        ,device="png"
#        ,path=paste0(img_dir,"/BoxPlots")
#        ,units="in", width=0.75, height=1.45, dpi=320)

grid.arrange(grobs = list(p1, p2, p3, p4), nrow=2, ncol=2)
```

#### Mixed Effect Models {.tabset .tabset-fade .tabset-pills}

__Model Setup:__ A repeated measures ANOVA (mixed effects model) will be used for all analyses.

Mixed Effect Model with Compound Symmetry in covariance matrix assumed. (Random intercept/Repeated Measure ANOVA).

__Model:__

$$
  Y_{ij} = (\mu_0 + \alpha_j) + (S_i + e_{ij})
$$

Where fixed effects are `ROI` and `ELA`, and random effects are `Animal` and `Voxel Number`.

Random effects here are used to control for Animal-to-Animal and Voxel-to-Voxel variance separately. 

##### Assessing Residuals 

```{R, fig.height = 4, fig.width = 6}
dir_tmp = paste0(output_prefix,"_cfos_ROI_analysis_M_S_n6")

if (!dir.exists(paste0(img_dir,"/Residuals/"))) {dir.create(paste0(img_dir,"/Residuals"))}
if (!dir.exists(paste0(img_dir,"/Residuals/",dir_tmp))) {dir.create(paste0(img_dir,"/Residuals/",dir_tmp))}

  lme.n.mte.rma <- lme(M_S ~ ROI
                     , random = list((~1|AnimNum),(~1|AnimNum))
                     , method = "REML"
                     , data = dat_cfos_roi_sub %>% filter(ELA %in% c("Normal"))
  )
  
  lme.e.mte.rma <- lme(M_S ~ ROI
                     , random = list((~1|AnimNum),(~1|AnimNum))
                     , method = "REML"
                     , data = dat_cfos_roi_sub %>% filter(ELA %in% c("ELA"))
  )
  
  
  for (group in c("ELA","Normal")) {
    if (group == "ELA"){
      lm.tmp = lme.e.mte.rma
    } else {
      lm.tmp = lme.n.mte.rma
    }
    
    cnt=1
    for (res in 1:dim(lm.tmp$residuals)[2]) {
      #### Residual Effect Type
      print(restype <- colnames(lm.tmp$residuals)[res])
      #### QQ Plot
      qqPlot(lm.tmp$residuals[,res], main=paste0("QQPlot for ",restype," in ", group))
      jpeg(file=paste0(paste0(img_dir,"/Residuals/"),dir_tmp,"/",output_prefix,"QQnorm_",restype,"-",group,"_n6.jpeg"),
         width = 4, height = 4, units = "in", res = 300)
      qqPlot(lm.tmp$residuals[,res], main=paste0("QQPlot for ",restype," in ", group))
      dev.off()
      ######## Bootstrapped Sampling Distribution of Residuals
      jpeg(file=paste0(paste0(img_dir,"/Residuals/"),dir_tmp,"/",output_prefix,"BootStrappedSampDist_",restype,"-",group,"_n6.jpeg"),
         width = 4, height = 4, units = "in", res = 300)
      bs_one_samp_dist(lm.tmp$residuals[,res])
      dev.off()
      #### Variance of Residuals by Fitted
      plot(lm.tmp$fitted[(1:dim(lm.tmp$residuals)[1])*cnt], lm.tmp$residuals[,res],
              main=paste0(restype," in", group, " Residuals by Fitted"))
      jpeg(file=paste0(paste0(img_dir,"/Residuals/"),dir_tmp,"/",output_prefix,"InHVar_Fitted",restype,"-",group,"_n6.jpeg"),
           width = 4, height = 4, units = "in", res = 300)
      plot(lm.tmp$fitted[(1:dim(lm.tmp$residuals)[1])*cnt], lm.tmp$residuals[,res],
              main=paste0(restype," in", group, " Residuals by Fitted"))
      dev.off()
      #### Variance Plot by ROI
      plot(lm.tmp$data$ROI, lm.tmp$residuals[,res],
           main=paste0(restype," in", group," Residuals by ROI"))
      jpeg(file=paste0(paste0(img_dir,"/Residuals/"),dir_tmp,"/",output_prefix,"InHVar_ROI",restype,"-",group,"_n6.jpeg"),
           width = 4, height = 4, units = "in", res = 300)
      plot(lm.tmp$data$ROI, lm.tmp$residuals[,res],
           main=paste0(restype," in", group," Residuals by ROI"))
      dev.off()
      cnt=cnt+1
    }
  }
```

##### Results of Linear Model and Post-Comparisons

```{R}
# ANOVA Results
  print("ELA")
  print(a.e.res <- Anova(lme.e.mte.rma, type="III"))
  print("Normal")
  print(a.n.res <- Anova(lme.n.mte.rma, type="III"))  

# Post-hoc Tests
## ELA
  #### Contrast Family ####1: Withing Group Differences between ROIs
  cont.cfos.e <- emmeans(lme.e.mte.rma, specs = "ROI")#, by = c("ELA"))
  ######## Calculate T/P-values
  results_cfos1 = cont.cfos.e %>% pairs(adjust = "none") %>% data.frame()
  ######## FDR Adjustment of P-values for Family of Pairwise Comparisons
  results_cfos1$p.value.fdr = ((cont.cfos.e %>% pairs(adjust = "fdr")) %>% as.data.frame())$p.value
  ######## Calculcate Cohen's D
  results_cfos1$CohD = abs(effectsize::t_to_d(as.data.frame(pairs(cont.cfos.e))$t.ratio,  
                                    rep(6,6),
                                    paired = T)$d
                 )
  ######## Update Data frame Results Output  
  results_cfos1 <- results_cfos1 %>%
    mutate(
      MeanDiff = (estimate) %>% round(.,2),
      SE = (SE) %>% round(.,2),
      T.value = round(t.ratio,2),
      CohD = round(CohD,2),
      P.value = round(p.value,5),
      P.value.fdr = round(p.value.fdr,5),
      SigLevel = ifelse(P.value.fdr > 0.1, "n.s.",
                        ifelse(P.value.fdr > 0.05, "~",
                               ifelse(P.value.fdr > 0.01, "*",
                                      ifelse(P.value.fdr > 0.001, "**", "***"))))
    ) %>%
    select(contrast,MeanDiff,SE,df,T.value,CohD,P.value,P.value.fdr,SigLevel)
  knitr::kable(results_cfos1, caption = "MEMRI M_S Differences between ROIs within ELA")  
  
  
## Normal
  #### Contrast Family ####1: Withing Group Differences between ROIs
  cont.cfos.n <- emmeans(lme.n.mte.rma, specs = "ROI")#, by = c("ELA"))
  ######## Calculate T/P-values
  results_cfos2 = cont.cfos.n %>% pairs(adjust = "none") %>% data.frame()
  ######## FDR Adjustment of P-values for Family of Pairwise Comparisons
  results_cfos2$p.value.fdr = ((cont.cfos.n %>% pairs(adjust = "fdr")) %>% as.data.frame())$p.value
  ######## Calculcate Cohen's D
  results_cfos2$CohD = abs(effectsize::t_to_d(as.data.frame(pairs(cont.cfos.n))$t.ratio,  
                                    rep(6,6),
                                    paired = T)$d
                 )
  ######## Update Data frame Results Output  
  results_cfos2 <- results_cfos2 %>%
    mutate(
      MeanDiff = (estimate) %>% round(.,2),
      SE = (SE) %>% round(.,2),
      T.value = round(t.ratio,2),
      CohD = round(CohD,2),
      P.value = round(p.value,5),
      P.value.fdr = round(p.value.fdr,5),
      SigLevel = ifelse(P.value.fdr > 0.1, "n.s.",
                        ifelse(P.value.fdr > 0.05, "~",
                               ifelse(P.value.fdr > 0.01, "*",
                                      ifelse(P.value.fdr > 0.001, "**", "***"))))
    ) %>%
    select(contrast,MeanDiff,SE,df,T.value,CohD,P.value,P.value.fdr,SigLevel)
  knitr::kable(results_cfos2, caption = "MEMRI M_S Differences between ROIs within Normal")  
```


#### T-tests

```{R}
df_test <- dat_cfos_roi_sub

g1.r1.dat = df_test %>% filter(ELA == "ELA", ROI == "CS") %>% pull(M_S)
g1.r2.dat = df_test %>% filter(ELA == "ELA", ROI == "MB") %>% pull(M_S)
bs_two_samp_diff_dist(g1.r1.dat,g1.r2.dat)
qqPlot(g1.r1.dat)
qqPlot(g1.r2.dat)
bartlett.test(M_S ~ ROI, data = df_test %>% filter(ELA == "ELA", ROI %in% c("CS","MB")))
tout = t.test(g1.r1.dat,g1.r2.dat, paired = T, var.equal = F)
print(tout)
effectsize::t_to_d(tout$statistic,6,paired=T) %>% abs() %>% pull(d) %>% round(.,2)

g1.r3.dat = df_test %>% filter(ELA == "ELA", ROI == "HYP") %>% pull(M_S)
g1.r4.dat = df_test %>% filter(ELA == "ELA", ROI == "THA") %>% pull(M_S)
bs_two_samp_diff_dist(g1.r3.dat,g1.r4.dat)
qqPlot(g1.r3.dat)
qqPlot(g1.r4.dat)
bartlett.test(M_S ~ ROI, data = df_test %>% filter(ELA == "ELA", ROI %in% c("HYP","THA")))
tout = t.test(g1.r3.dat,g1.r4.dat, paired = T, var.equal = T)
print(tout)
effectsize::t_to_d(tout$statistic,6,paired=T) %>% abs() %>% pull(d) %>% round(.,2)

g2.r1.dat = df_test %>% filter(ELA == "Normal", ROI == "CS") %>% pull(M_S)
g2.r2.dat = df_test %>% filter(ELA == "Normal", ROI == "MB") %>% pull(M_S)
bs_two_samp_diff_dist(g2.r1.dat,g2.r2.dat)
qqPlot(g2.r1.dat)
qqPlot(g2.r2.dat)
bartlett.test(M_S ~ ROI, data = df_test %>% filter(ELA == "Normal", ROI %in% c("CS","MB")))
t.test(g2.r1.dat,g2.r2.dat, paired = F, var.equal = T)

g2.r3.dat = df_test %>% filter(ELA == "Normal", ROI == "HYP") %>% pull(M_S)
g2.r4.dat = df_test %>% filter(ELA == "Normal", ROI == "THA") %>% pull(M_S)
bs_two_samp_diff_dist(g2.r3.dat,g2.r4.dat)
qqPlot(g2.r3.dat)
qqPlot(g2.r4.dat)
bartlett.test(M_S ~ ROI, data = df_test %>% filter(ELA == "Normal", ROI %in% c("HYP","THA")))
t.test(g2.r3.dat,g2.r4.dat, paired = F, var.equal = F)
```


## Correlations between c-fos and MEMRI

### Load Data      

Data is reloaded here

#### Load and Process c-Fos Counts
```{R}
filename <- "240411_c-fos_GridCounts-TWU.xlsx"
dat_cfos_count = read.xlsx(
  xlsxFile = paste0(wdir,"/R_Analysis/",filename)
  , sheet = "long.df.voxels"
  , colNames = T
  , na.strings = NA)

#### Process Data
#### FORMAT DATA FRAME
dat_cfos_count <- dat_cfos_count %>%
  mutate(
    ELA = factor(
      Group,
      levels = c("ELA","Normal"),
      labels = c("ELA","Normal")),
    ROI = factor(ROI,
                 levels = c("CS","MB","HYP","THA"),
                 labels = c("CS","MB","HYP","THA")
    ),
    AnimNum = factor(ID,
                     levels = c("03","04","05","06","07","08","A","D","F","I","K"),
                     labels = c(1:6,13,14,15,17,18)),
    VoxelNum = factor(VoxelNum),
    Count = as.numeric(cfos_count),
    SqrCnt = sqrt(Count)
  ) %>% 
  arrange(ROI,ELA,VoxelNum) %>%
  select(AnimNum,VoxelNum,ELA,ROI,Count,SqrCnt)
knitr::kable(summary(dat_cfos_count))
str(dat_cfos_count)
```

__Summarize Voxel-wise c-fos Data within an ROI__

```{R}
dat_cfos_count_sum2 <- dat_cfos_count %>%
  group_by(
    ROI, ELA, AnimNum
  ) %>%
  summarise(
    M_c = mean(SqrCnt) %>% round(.,2),
    SD_c = sd(SqrCnt) %>% round(.,2),
    SEM_c = (SD_c / sqrt(n())) %>% round(.,2)
  ) %>% data.frame()
knitr::kable(summary(dat_cfos_count_sum2), caption = "Summary of Data by Individual")
```

#### Load and Process MEMRI ROI Intensities
```{R}
filename <- "ELA_Normal_cfos_ROI.csv"
header <- c("IMAGE","ROI"
            ,c("ELA","Condition","VoxelNum") ############ USER INPUT NEEDED
            ,"MEAN","BLANK") 
dat_cfos_roi = read.csv2(paste0(dat_dir,"/",filename)
                         ,header = F
                         ,na.strings = NA
                         ,sep = ","
                         ,col.names = header)
dat_cfos_roi = dat_cfos_roi[,-which(colnames(dat_cfos_roi) == "BLANK")] 

#### FORMAT DATA FRAME
dat_cfos_roi <- dat_cfos_roi %>%
  mutate(
    Condition = factor(
      Condition,
      levels = c("D9")),
    ELA = factor(
      ELA,
      levels = c("ELA","Normal"),
      labels = c("ELA","Normal")),
    ROI = factor(ROI,
                 levels = c("CS","MB","HYP","THA"),
                 labels = c("CS","MB","HYP","THA")
    ),
    ID = factor(parse_number(IMAGE)),
    VoxelNum = factor(VoxelNum),
    MEAN = as.numeric(MEAN)
  ) %>%
  arrange(ROI,ELA,Condition,VoxelNum) %>%
  group_by(
    Condition,
    ROI,
    VoxelNum
  ) %>%
  mutate(
    AnimNum = factor(1:n())
  ) %>%
  ungroup() %>%
  select(AnimNum,VoxelNum,ELA,Condition,ROI,MEAN) %>%
  filter(
    AnimNum %in% c(1:6,13,14,15,17,18)
  )
```



__Summarize Voxel-wise MEMRI Data within an ROI__

```{R}
dat_cfos_roi_sum2 <- dat_cfos_roi %>% 
  filter(
    (Condition == "D9"),
    ROI %in% c("CS","MB","HYP","THA")
  ) %>%
  mutate(
    Condition = droplevels.factor(Condition),
    ROI = droplevels.factor(ROI)
  ) %>% 
  group_by(
    ROI, ELA, AnimNum
  ) %>% 
  summarize(
    M_SI = mean(MEAN) %>% round(.,2),
    SD_SI = sd(MEAN) %>% round(.,2),
    SEM_SI = (SD_SI / sqrt(n())) %>% round(.,2)
  ) %>% data.frame()
knitr::kable(summary(dat_cfos_roi_sum2))
dim(dat_cfos_roi_sum2)
```

__Combine Summarized Data ROI-wise__

```{R}
dat_combined_cfos2 = cbind.data.frame(dat_cfos_count_sum2,dat_cfos_roi_sum2 %>% select(M_SI, SD_SI, SEM_SI))
```

### Graph Scatter Plots and Analyze Correlations

```{R}
plot(dat_combined_cfos2 %>% filter(ROI == "CS", ELA == "Normal") %>% pull(M_c),
     dat_combined_cfos2 %>% filter(ROI == "CS", ELA == "Normal") %>% pull(M_SI),
     ylab="MEMRI SI",xlab="c-fos+ Nuclei (Sqrt / 100mm^2)", col="blue",pch=16,cex=2,
     main="CS - Normal")
cor.test(dat_combined_cfos2 %>% filter(ROI == "CS", ELA == "Normal") %>% pull(M_c),
         dat_combined_cfos2 %>% filter(ROI == "CS", ELA == "Normal") %>% pull(M_SI),
         method = "spearman")

plot(dat_combined_cfos2 %>% filter(ROI == "MB", ELA == "Normal") %>% pull(M_c),
     dat_combined_cfos2 %>% filter(ROI == "MB", ELA == "Normal") %>% pull(M_SI),
     ylab="MEMRI SI",xlab="c-fos+ Nuclei (Sqrt / 100mm^2)", col="blue",pch=16,cex=2,
     main="MB - Normal")
cor.test(dat_combined_cfos2 %>% filter(ROI == "MB", ELA == "Normal") %>% pull(M_c),
         dat_combined_cfos2 %>% filter(ROI == "MB", ELA == "Normal") %>% pull(M_SI),
         method = "spearman")

plot(dat_combined_cfos2 %>% filter(ROI == "HYP", ELA == "Normal") %>% pull(M_c),
     dat_combined_cfos2 %>% filter(ROI == "HYP", ELA == "Normal") %>% pull(M_SI),
     ylab="MEMRI SI",xlab="c-fos+ Nuclei (Sqrt / 100mm^2)", col="blue",pch=16,cex=2,
     main="HYP - Normal")
cor.test(dat_combined_cfos2 %>% filter(ROI == "HYP", ELA == "Normal") %>% pull(M_c),
         dat_combined_cfos2 %>% filter(ROI == "HYP", ELA == "Normal") %>% pull(M_SI),
         method = "spearman")

plot(dat_combined_cfos2 %>% filter(ROI == "THA", ELA == "Normal") %>% pull(M_c),
     dat_combined_cfos2 %>% filter(ROI == "THA", ELA == "Normal") %>% pull(M_SI),
     ylab="MEMRI SI",xlab="c-fos+ Nuclei (Sqrt / 100mm^2)", col="blue",pch=16,cex=2,
     main="THA - Normal")
cor.test(dat_combined_cfos2 %>% filter(ROI == "THA") %>% pull(M_c),
         dat_combined_cfos2 %>% filter(ROI == "THA") %>% pull(M_SI),
         method = "spearman")



plot(dat_combined_cfos2  %>% pull(M_c),
     dat_combined_cfos2  %>% pull(M_SI),
     ylab="MEMRI SI",xlab="c-fos+ Nuclei ( / 100mm^2)", col="blue",pch=16,cex=2,
     main="All ROIs - Normal")
cor.test(dat_combined_cfos2  %>% pull(M_c),
         dat_combined_cfos2 %>% pull(M_SI),
         method = "pearson")
glm(M_SI ~ M_c, data=dat_combined_cfos, family = "poisson") %>% summary()
```

### Bootstap Resampling / Permutation Testing

#### Individual ROIs

```{R}
for (r in unique(dat_combined_cfos2$ROI)) {
  # r = "All Segments"
  cat(paste0("\n",r,"\n"))
  dat_combined_boot = dat_combined_cfos2 %>% filter(ELA == "Normal",ROI == r)
  
  Nboot = 1e4
  samp_ind_boot = list()
  mean_boot = data.frame(
    M_c = rep(NA,Nboot),
    M_SI = rep(NA,Nboot),
    cor = rep(NA,Nboot)
  )
  for (i in 1:Nboot) {
    # cat(paste0(round((i/Nboot)*100,0),"% complete","\r"))
    samp_ind_boot[[i]] = sample(1:nrow(dat_combined_boot),size = nrow(dat_combined_boot), replace = T)
    mean_boot$M_c[i] = dat_combined_boot$M_c[samp_ind_boot[[i]]] %>% mean()
    mean_boot$M_SI[i] = dat_combined_boot$M_SI[samp_ind_boot[[i]]] %>% mean()
    mean_boot$cor[i] = cor(dat_combined_boot$M_c[samp_ind_boot[[i]]],dat_combined_boot$M_SI[samp_ind_boot[[i]]], method = "pearson")
  }
  # Random Sample
  samp_ind_bootr = list()
  mean_bootr = data.frame(
    M_c = rep(NA,Nboot),
    M_SI = rep(NA,Nboot),
    cor = rep(NA,Nboot)
  )
  for (i in 1:Nboot) {
    # cat(paste0(round((i/Nboot)*100,0),"% complete","\r"))
    samp_ind_bootr[[i]] = sample(1:nrow(dat_combined_boot),size = nrow(dat_combined_boot), replace = F)
    mean_bootr$M_c[i] = dat_combined_boot$M_c[samp_ind_boot[[i]]] %>% mean()
    mean_bootr$M_SI[i] = dat_combined_boot$M_SI %>% mean()
    mean_bootr$cor[i] = cor(dat_combined_boot$M_c[samp_ind_boot[[i]]],dat_combined_boot$M_SI, method = "pearson")
  }
  pval = length(which((mean_boot$cor %>% mean(.,na.rm=T)) <= mean_bootr$cor)) / length(mean_bootr$cor)
  pval = ifelse(pval > 0.05,paste0("= ",pval),ifelse(pval > 0.01, "< 0.05" ,ifelse(pval > 0.001, "< 0.01" ,ifelse(pval > 0.0001, "< 0.001", "< 0.0001"))))
  plot(mean_boot$M_c,mean_boot$M_SI,
       main = paste0(r),
       xlab = "Sqrt Count",
       ylab = "MEMRI SI")
  cat(paste0("\n Correlation of Resampled Means = ",cor(mean_boot$M_c,mean_boot$M_SI) %>% round(.,2),"\n"))
  cat(paste0("\n Mean of Resampled Correlations = ",mean_boot$cor %>% mean(.,na.rm=T) %>% round(.,2),"\n"))
  
  cat(paste0("\n Permutation p-value ",pval,"\n"))

}
```

#### All ROIs Combined

```{R}
  r = "All ROIs"
  grp = "Normal"
  cat(paste0("\n",r,"\n"))
  dat_combined_boot = dat_combined_cfos2 %>% filter(ELA == grp) %>% select(-c(SD_c,SEM_c,SD_SI,SEM_SI))
  
  if (grp == "Normal"){
    coltmp = "cyan4"
  } else {
    coltmp = "goldenrod2"
  }
  
  Nboot = 1e4
  samp_ind_boot = matrix(NA, nrow = nrow(dat_combined_boot), ncol = Nboot) 
  mean_boot = data.frame(
    M_c = rep(NA,Nboot),
    M_SI = rep(NA,Nboot),
    cor = rep(NA,Nboot)
  )
  for (i in 1:Nboot) {
    # colnames(samp_ind_boot)[i] = paste0("Resample.",i)
    cat(paste0(round((i/Nboot)*100,0),"% complete","\r"))
    samp_ind_boot[,i] = sample(1:nrow(dat_combined_boot), size = nrow(dat_combined_boot), replace = T)
    mean_boot$M_c[i] = dat_combined_boot$M_c[samp_ind_boot[,i]] %>% mean()
    mean_boot$M_SI[i] = dat_combined_boot$M_SI[samp_ind_boot[,i]] %>% mean()
    mean_boot$cor[i] = cor(dat_combined_boot$M_c[samp_ind_boot[,i]],dat_combined_boot$M_SI[samp_ind_boot[,i]], method = "pearson")
  }
  # write.csv(samp_ind_boot,paste0(wdir,"/OutputData/Tables/250701_Bootstrap_Resamples.csv"))
  # Random Sample
  samp_ind_bootr = matrix(NA, nrow = nrow(dat_combined_boot), ncol = Nboot) #%>% as.data.frame()
  mean_bootr = data.frame(
    M_c = rep(NA,Nboot),
    M_SI = rep(NA,Nboot),
    cor = rep(NA,Nboot)
  )
  for (i in 1:Nboot) {
    # colnames(samp_ind_bootr)[i] = paste0("Permutation",i)
    cat(paste0(round((i/Nboot)*100,0),"% complete","\r"))
    samp_ind_bootr[,i] = sample(1:nrow(dat_combined_boot), size = nrow(dat_combined_boot), replace = F)
    mean_bootr$M_c[i] = dat_combined_boot$M_c[samp_ind_boot[,i]] %>% mean()
    mean_bootr$M_SI[i] = dat_combined_boot$M_SI %>% mean()
    mean_bootr$cor[i] = cor(dat_combined_boot$M_c[samp_ind_boot[,i]],dat_combined_boot$M_SI, method = "pearson")
  }
  # write.csv(samp_ind_boot,paste0(wdir,"/OutputData/Tables/250701_Permutation_Resampl of_Counts.csv"))
  real_cor = cor(dat_combined_boot$M_c,dat_combined_boot$M_SI)
  pval = length(which(cor(dat_combined_boot$M_c,dat_combined_boot$M_SI) <= mean_bootr$cor)) / length(mean_bootr$cor)
  pval = ifelse(pval > 0.05,paste0("= ",pval),ifelse(pval > 0.01, "< 0.05" ,ifelse(pval > 0.001, "< 0.01" ,ifelse(pval > 0.0001, "< 0.001", "< 0.0001"))))
  # plot(mean_boot$M_c,mean_boot$M_SI,
  #      main = paste0(r),
  #      xlab = "Sqrt Count",
  #      ylab = "MEMRI SI")
  # hist(mean_bootr$cor)
  # hist(mean_boot$cor)
  cat(paste0("\n Correlation of Original Sample = ",real_cor %>% round(.,3),"\n"))
  cat(paste0("\n Permutation Testing: p ",pval,"\n"))
  cat(paste0("\n Mean of Resampled Correlations = ",mean_boot$cor %>% mean(.,na.rm=T) %>% round(.,3),"\n"))
  cat(paste0("\n 95% CI of Resampled Correlations: [",quantile(mean_boot$cor, probs=c(0.025)) %>% as.vector() %>% round(.,3),", ",quantile(mean_boot$cor, probs=c(0.975)) %>% as.vector() %>% round(.,3),"]\n"))

  mean_boot$Dist = "Paired"
  mean_bootr$Dist = "Random"
  
  dat_boot = rbind.data.frame(mean_boot, mean_bootr)
  dat_boot <- dat_boot %>%
    mutate(
      Dist = factor(Dist, levels = c("Random","Paired"))
    )

  p = ggplot(data = dat_boot, aes(x = cor, fill = Dist, color = Dist)) +
    geom_histogram(alpha = 0.25, position = 'identity', bins = 100, linewidth = 0.5) +
    geom_vline(xintercept = real_cor, color = "black", linetype = "solid", linewidth = 0.6, alpha = 1) +
    scale_fill_manual(values=c("grey50", coltmp)) +
    scale_color_manual(values=c("grey50", coltmp)) +
    scale_x_continuous(limits = c(-0.8,1.1), breaks = seq(-0.75,1,0.25), expand=c(0,0,0,0)) + 
    scale_y_continuous(limits = c(0,900), breaks = seq(0,800,200), expand=c(0,0,0,0)) +
    theme_bw() +
    labs(x = "Correlation Coefficient",
         y = "Frequency") + 
    theme(
      legend.position = "none",
      axis.title = element_blank(),
      axis.text = element_text(family="sans",size=8,face="bold")
    )
  p
  # ggsave(filename=paste0("250701_cfos_MEMRI_Correlation_Histograms",grp,".png")
  #      ,plot=p
  #      ,device="png"
  #      ,path=img_dir
  #      ,units="in", width=3.2, height=1.6, dpi=320)
  
  coefs = lm((M_SI*10^-3) ~ (M_c), data=mean_boot) %>% coefficients() %>% as.numeric() %>% as.vector()
  
  p = ggplot(data = mean_boot, aes(x = M_c, y = M_SI*10^-3)) +
    geom_point(color = coltmp, alpha = 0.1, position = 'identity', size = 0.2) +
    geom_function(fun=Vectorize(function(x) {
    if( x < 0)
      return(NA)
    else
      return((x)*coefs[2] + coefs[1])
    }), color="black", linetype = "solid", linewidth = 0.5, alpha = 1) +
    annotate("text", label=paste0("r = ",mean_boot$cor %>% mean(.,na.rm=T) %>% round(.,3),"0"), x = 1.0, y = 8.5, size = 2.75) +
    scale_x_continuous(limits = c(0.75,2.75), breaks = seq(1,2.5,0.5), expand=c(0,0,0,0)) +
    scale_y_continuous(limits = c(7.400,9.05), breaks = seq(7.500,9,0.500), expand=c(0,0,0,0)) +
    theme_bw() +
    labs(x = "",
         y = "") +
    theme(
      legend.position = "none",
      axis.title = element_blank(),
      axis.text = element_text(family="sans",size=8,face="bold")
    )
  p
  # ggsave(filename=paste0("250701_cfos_MEMRI_CorrelationScatter",grp,".png")
  #      ,plot=p
  #      ,device="png"
  #      ,path=img_dir
  #      ,units="in", width=3.2, height=1.6, dpi=320)
  
  if (grp == 'Normal' ){
    Nmboot = mean_boot
    Nmboot$grp = rep("Normal") %>% factor(.,levels=c("Normal","ELA"))
  } else if (grp == "ELA") {
    Emboot = mean_boot
    Emboot$grp = rep("ELA") %>% factor(.,levels=c("Normal","ELA"))
  }
  if (exists("Nmboot") && exists("Emboot")) {
    comb_mean_boot = rbind.data.frame(Nmboot,Emboot)
    lm.out = lm((M_SI*10^-3) ~ M_c * grp, data=comb_mean_boot)
    summary(lm.out)
    coefs = lm.out %>% coefficients() %>% as.numeric() %>% as.vector()
    
    p = ggplot(data = comb_mean_boot, aes(x = M_c, y = M_SI*10^-3, color = grp)) +
    geom_point(alpha = 0.05, position = 'identity', size = 0.2) +
    geom_function(fun=Vectorize(function(x) {
    if(x < 0.9)
      return(NA)
    else if (x > 2.6)
      return(NA)
    else
      return(coefs[1] + x*coefs[2])
    }), color="cyan4", linetype = "solid", linewidth = 0.5, alpha = 0.75) + 
    geom_function(fun=Vectorize(function(x) {
    if(x < 0.9)
      return(NA)
    else if (x > 2.6)
      return(NA)
    else
      return(coefs[1] + coefs[3] + x*(coefs[2] + coefs[4]))
    }), color="goldenrod3", linetype = "solid", linewidth = 0.5, alpha = 75) +
    annotate("text", label=paste0("Adj.~R^{2}==",summary(lm.out)$adj.r.squared %>% round(.,3)), parse=T, x = 1.25, y = 8.75, size = 2.75) +
    scale_x_continuous(limits = c(0.75,2.75), breaks = seq(1,2.5,0.5), expand=c(0,0,0,0)) +
    scale_y_continuous(limits = c(7.400,9.05), breaks = seq(7.500,9,0.500), expand=c(0,0,0,0)) +
    scale_color_manual(values = c("cyan3","goldenrod2")) +
    theme_bw() +
    labs(x = "",
         y = "") +
    theme(
      legend.position = "none",
      axis.title = element_blank(),
      axis.text = element_text(family="sans",size=8,face="bold")
    )
    p
    ggsave(filename=paste0("250701_cfos_MEMRI_CorrelationScatter_MulReg.png")
     ,plot=p
     ,device="png"
     ,path=img_dir
     ,units="in", width=3.2, height=1.6, dpi=320)
  }
  
  
  # ggstatsplot::ggscatterstats(data = mean_boot, x = M_c, y = M_SI,
  #                             point.args = list(size = 3, alpha = 0.1, stroke = 0, color = "cyan4"),
  #                             smooth.line.args = list(linewidth = 1.5, color = "cyan4", method = "lm", formula = y ~ x),
  #                             xsidehistogram.args = list(fill = "violet",color="violet",alpha=0.25),
  #                             ysidehistogram.args = list(fill = "cyan4",color="cyan4",alpha=0.25),
  #                             xlab = "c-fos+ Nuclei",
  #                             ylab = "MEMRI SI")
```


### Save Data as EXCEL
```{R}
if (!dir.exists(paste0(wdir,"/OutputData/Tables/"))) { dir.create(paste0(wdir,"/OutputData/Tables/"))}
if (!file.exists(paste0("OutputData/Tables/R_Processed_cfos_MEMRI_ROI_Correlation.xlsx"))) {
  wb <- createWorkbook()
  addWorksheet(wb, "Input_cfos")
  addWorksheet(wb, "Input_MEMRI")
  addWorksheet(wb, "Combined_Voxelwise")
  addWorksheet(wb, "Combined_Averaged")
  writeDataTable(wb
                 , sheet = "Input_cfos"
                 , dat_cfos_count %>% select(-SqrCnt)
                 , colNames = T)
  writeDataTable(wb
                 , sheet = "Input_MEMRI"
                 , dat_cfos_roi
                 , colNames = T)
  writeDataTable(wb
                 , sheet = "Combined_Voxelwise"
                 , dat_combined_cfos
                 , colNames = T)
  writeDataTable(wb
                 , sheet = "Combined_Averaged"
                 , dat_combined_cfos2
                 , colNames = T)
  saveWorkbook(wb, file =  paste0("OutputData/Tables/R_Processed_cfos_MEMRI_ROI_Correlation.xlsx"), overwrite = F)
}  
```